### ISSUE TITLE
Crash in init

### ISSUE THREAD

**Issue by NirpE** [dlew/joda-time-android#183]
I got reported couple of crashes:

> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.res.StringBlock.get(int)' on a null object reference
       at android.content.res.AssetManager.getResourceValue(AssetManager.java:213)
       at android.content.res.Resources.getValue(Resources.java:1423)
       at android.content.res.Resources.getValue(Resources.java:1412)
       at android.content.res.Resources.openRawResource(Resources.java:1330)
       at android.content.res.Resources.openRawResource(Resources.java:1306)
       at net.danlew.android.joda.ResourceZoneInfoProvider.openResource(ResourceZoneInfoProvider.java:119)
       at net.danlew.android.joda.ResourceZoneInfoProvider.(ResourceZoneInfoProvider.java)
       at net.danlew.android.joda.JodaTimeAndroid.init(JodaTimeAndroid.java:39)
...

These are from production build, using obfuscation.

Devices are:

ZTE A2017U 
OnePlus One
samsung Galaxy Note5
asus ZenFone 2 Laser (ZE550KLA)
asus ZenFone 2 Laser (ZE500KG)

Any idea why this happens? I have not found a way to reproduce this.

Thanks.

**Comment by dlew** [comment]
If you're using obfuscation, then you might be renaming the assets that joda-time-android depends on. Theoretically, we should be keeping you from renaming the assets using our keep.xml: https://github.com/dlew/joda-time-android/blob/master/library/src/main/res/raw/joda_keep.xml

Could you check your APK with the APK analyzer and see if the assets are being renamed? They should all look something like joda_america_chicago or something.

**Comment by NirpE** [comment]
Hi, I checked the APK raw resources. All look to be fine. Can the OS do something weird here like rename those resources when the app is installed?

<img width="310" alt="screen shot 2017-05-18 at 15 35 42" src="https://cloud.githubusercontent.com/assets/3623617/26220233/da423b80-3bdf-11e7-8461-b8b1f3463847.png">

**Comment by dlew** [comment]
I haven't heard of an OS renaming resources... I'm honestly a bit at a loss here.

**Comment by NirpE** [comment]
You are not the only one being lost with this issue 👍
