### ISSUE TITLE
RuntimeException Caused by java.io.NotSerializableException org.joda.time.c0.b$d 

### ISSUE THREAD

**Issue by flopshot** [dlew/joda-time-android#253]
Hello,

I am seeing crash logs in production when parceling POJOS that have `DateTime` as a field. Has anyone seen this type of error before? Is this an issue with pro guard / R8 perhaps?

I'm currently using version joda time 2.10.3 in AS 3.6 with AGP 3.5.3

```
Fatal Exception: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.joda.time.b)
       at android.os.Parcel.writeSerializable(Parcel.java:1714)
       at com.marianatek.gritty.repository.models.ClassEntity.writeToParcel(ClassEntity.java:17)
       at com.marianatek.gritty.repository.models.ScheduledClass.writeToParcel(ScheduledClass.java:8)
       at com.marianatek.gritty.repository.models.Reservation.writeToParcel(Reservation.java:18)
       at android.os.Parcel.writeParcelable(Parcel.java:1683)
       at android.os.Parcel.writeValue(Parcel.java:1589)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
       at android.os.Bundle.writeToParcel(Bundle.java:1233)
       at android.os.Parcel.writeBundle(Parcel.java:915)
       at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:125)
       at android.os.Parcel.writeTypedObject(Parcel.java:1516)
       at android.os.Parcel.writeTypedList(Parcel.java:1395)
       at android.os.Parcel.writeTypedList(Parcel.java:1380)
       at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51)
       at android.os.Parcel.writeParcelable(Parcel.java:1683)
       at android.os.Parcel.writeValue(Parcel.java:1589)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
       at android.os.Bundle.writeToParcel(Bundle.java:1233)
       at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3942)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6952)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by java.io.NotSerializableException: org.joda.time.c0.b$d
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
       at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
       at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
       at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
       at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
       at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
       at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
       at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
       at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
       at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
       at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
       at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
       at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
       at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
       at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
       at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
       at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
       at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
       at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
       at android.os.Parcel.writeSerializable(Parcel.java:1709)
       at com.marianatek.gritty.repository.models.ClassEntity.writeToParcel(ClassEntity.java:17)
       at com.marianatek.gritty.repository.models.ScheduledClass.writeToParcel(ScheduledClass.java:8)
       at com.marianatek.gritty.repository.models.Reservation.writeToParcel(Reservation.java:18)
       at android.os.Parcel.writeParcelable(Parcel.java:1683)
       at android.os.Parcel.writeValue(Parcel.java:1589)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
       at android.os.Bundle.writeToParcel(Bundle.java:1233)
       at android.os.Parcel.writeBundle(Parcel.java:915)
       at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:125)
       at android.os.Parcel.writeTypedObject(Parcel.java:1516)
       at android.os.Parcel.writeTypedList(Parcel.java:1395)
       at android.os.Parcel.writeTypedList(Parcel.java:1380)
       at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51)
       at android.os.Parcel.writeParcelable(Parcel.java:1683)
       at android.os.Parcel.writeValue(Parcel.java:1589)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
       at android.os.Bundle.writeToParcel(Bundle.java:1233)
       at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3942)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6952)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by dlew** [comment]
I'm going to close this because it's an issue with [joda-time](https://github.com/JodaOrg/joda-time) (the dependency of this library), not joda-time-android.

That said, joda-time is not an Android-exclusive library. You may very well have to add some proguard rules for the base joda-time depending on how you're using Proguard. I don't know that I want to setup too many rules in joda-time-android because I don't want to overreach and keep more than people using joda-time-android want to keep.

Also, worth noting that most people don't use `Serializable` because it's pretty awful on Android. I suggest a different marshalling method.

**Comment by flopshot** [comment]
Fair enough. 

I will say that in my application, I use Kotlin's `@Parcelize` annotation to parcel my data classes, which is compatible with any `Serializable`. It's not a stretch to think others in the Android community would also run into this issue if they are trying to `@Parcelize` a data class with a `DateTime` field. 

As per this [so post](https://stackoverflow.com/questions/52949081/how-to-stop-proguard-from-removing-joda-time-resources-on-android), which does not explicitly reference my error, I will add the mentioned proguard rules and give an update afterwards. Hopefully that will stop the crashes I'm seeing in Crashlytics.

**Comment by dlew** [comment]
Definitely understandable, but I also don't want to `-keep all` because that's unfriendly to someone who might be trying to use joda-time in a minimal manner.

FYI, you can write your own custom parcel serializers - see "custom types serializers" on this post: https://medium.com/@BladeCoder/a-study-of-the-parcelize-feature-from-kotlin-android-extensions-59a5adcd5909

**Comment by flopshot** [comment]
**UPDATE:**
5 days ago we upgraded to joda-time-android version `2.10.6` and added these Pro-guard rules:
```
#proguard-rules.pro

-dontwarn org.joda.convert.**
-dontwarn org.joda.time.**
-keep class org.joda.time.** { *; }
-keep interface org.joda.time.** { *; }
```
 Since then, we have not seen the above crash in production.
