### ISSUE TITLE
DateTimeFormatter.fullDateTime() not entirely compatible with android

### ISSUE THREAD

**Issue by Thorbear** [dlew/joda-time-android#30]
The default formats provided through JodaTime are not entirely compatible with Android.

A simple demonstration is to use the DateTimeFormatter.fullDateTime() method in your code, and have the phone set to use Suomi as language, which will fail because the android version of SimpleDateFormat includes 'c' for "stand-alone day of week" which is not supported by JodaTime.

**Comment by Thorbear** [comment]
A dirty workaround for this could be to rewrite the method parsePatternTo() in DateTimeFormat to handle 'c' and 'L' as 'E' and 'M' respectively.

**Comment by dlew** [comment]
When you say "fail", what do you mean? Is the output incorrect? Does it crash?

Regardless, I would avoid using `DateTimeFormatter` anyways, since it doesn't take into account all of the different Android configurations (such as day/month/year order and 12h vs. 24h). Better to use `DateUtils` included with this library.

**Comment by Thorbear** [comment]
It will fail in the sense that whenever the returned formatter is used it will throw an IllegalArgumentException, because it doesn't recognize the formatting 'cccc'.

Avoiding DateTimeFormatter might be a good suggestion for JodaTime usage on Android in general, but I feel this is something that should at least be pointed out in some release notes, since it all happens inside the library.

**Comment by dlew** [comment]
I'm wondering if the best solution would be to add support for `c` (and while we're at it, `L`) to the joda-time formatter. Then one can keep using it.

For posterity, here's the crash logs:

     Caused by: java.lang.IllegalArgumentException: Illegal pattern component: cccc
            at org.joda.time.format.DateTimeFormat.parsePatternTo(DateTimeFormat.java:566)
            at org.joda.time.format.DateTimeFormat.createFormatterForPattern(DateTimeFormat.java:687)
            at org.joda.time.format.DateTimeFormat.forPattern(DateTimeFormat.java:177)
            at org.joda.time.format.DateTimeFormat$StyleFormatter.getFormatter(DateTimeFormat.java:833)
            at org.joda.time.format.DateTimeFormat$StyleFormatter.printTo(DateTimeFormat.java:810)
            at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:684)
            at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:521)
            at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:625)
            at net.danlew.android.joda.sample.JodaSampleActivity.test(JodaSampleActivity.java:56)
            at net.danlew.android.joda.sample.JodaSampleActivity.onCreate(JodaSampleActivity.java:38)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
