### ISSUE TITLE
Cannot use alongside com.fasterxml.jackson.datatype:jackson-datatype-joda:2.5.0

### ISSUE THREAD

**Issue by DarthCrap** [dlew/joda-time-android#31]
Hi

It is highly likely I am being very stupid, but when including both net.danlew:android.joda:2.7.0 (To get your library) and com.fasterxml.jackson.datatype:jackson-datatype-joda:2.5.0 (To get jackson to joda serializaion), Dex balks at the ":app:dexDebug" stage of gradle compilation, and refuses to work, reporting

	com.android.dex.DexException: Multiple dex files define Lorg/joda/time/Chronology;
		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)

Do you think this is me doing something stupid, or something that can be fixed in the library?

Thanks

**Comment by dlew** [comment]
I'm not 100% sure this is the reason, but it looks like it's including joda-time twice (once as a dependency for joda-time-android, once for jackson-datatype-joda). I think this is happening because jackson uses joda-time 2.2 (whereas we're using joda-time 2.7).

You can always exclude the joda-time dependency from jackson-datatype-joda:

    compile('com.fasterxml.jackson.datatype:jackson-datatype-joda:2.5.0') {
        exclude module: 'joda-time'
    }

Might also want to submit a PR to jackson-datatype-joda updating their dependency.

**Comment by DarthCrap** [comment]
Thanks.
I should have thought to use an exclude, which I should have done!
I added it in and presto, it works.
