### ISSUE TITLE
having "Resource not found: "org/joda/time/tz/data/ZoneInfoMap" on latest v2.12.1.1 (on testing env)

### ISSUE THREAD

**Issue by eriknyk** [dlew/joda-time-android#329]
I have some unit tests using joda DateTime and Period and methods are being executed well no broken executions however the following output is printed in console, so it is not causing that tests not passed but only I wanted let you know that is happening.

About my dev env:
I'm using  junit 5 (5.9.1)
using kotlin 1.8.10

More exactly inclusions

```
    testImplementation "org.jetbrains.kotlin:kotlin-test"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit5"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.1'
```

The output:

```
java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@67424e82
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:225)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:138)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:97)
	at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:557)
	at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:451)
	at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:369)
	at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:177)
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
	at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:269)
	at org.joda.time.base.BasePeriod.<init>(BasePeriod.java:256)
	at org.joda.time.Period.<init>(Period.java:301)
	at org.joda.time.Period.<clinit>(Period.java:65)
```
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/205721/222294108-45ba61f3-81cf-4c2b-867e-2d674df570be.png">

**Comment by dlew** [comment]
Are the tests being run on an Android device (integration test) or is it being run in a pure JVM? If it's the latter, chance are you need to include a version of joda-time that includes tzdata - the version that joda-time-android pulls in lacks tzdata (since joda-time-android provides it instead), but the joda-time-android tzdata only works on Android devices.

**Comment by eriknyk** [comment]
Hi @dlew, no it's not running on an android device,it's happening running on my local machine on android studio

**Comment by dlew** [comment]
You want to use the non-Android, joda-time artifact for your tests then (since they include tzdata for JVM). And then continue using joda-time-android on the actual implementation of the app.
