### ISSUE TITLE
R8 fullMode causes NoSuchMethodException

### ISSUE THREAD

**Issue by samoylenkodmitry** [dlew/joda-time-android#336]
```
08-10 14:17:09.244 22340 22456 E assert  : Trace: java.lang.RuntimeException: java.lang.NoSuchMethodException: ru.ivi.client.utils.DateTimeZoneProvider.<init> []
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTimeZone.getDefaultProvider(SourceFile:74)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTimeZone.getProvider(SourceFile:11)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTimeZone.forTimeZone(SourceFile:29)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTimeZone.getDefault(SourceFile:29)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.chrono.ISOChronology.getInstance(SourceFile:1)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.base.BaseDateTime.<init>(SourceFile:1)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTime.<init>(SourceFile:1)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTime.now(SourceFile:1)
```
```
08-10 14:17:09.244 22340 22456 E assert  : Caused by: java.lang.NoSuchMethodException: ru.ivi.client.utils.DateTimeZoneProvider.<init> []
08-10 14:17:09.244 22340 22456 E assert  : 	at java.lang.Class.getConstructor0(Class.java:2363)
08-10 14:17:09.244 22340 22456 E assert  : 	at java.lang.Class.getConstructor(Class.java:1759)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTimeZone.getDefaultProvider(SourceFile:36)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTimeZone.getProvider(SourceFile:11)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTimeZone.forTimeZone(SourceFile:29)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTimeZone.getDefault(SourceFile:29)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.chrono.ISOChronology.getInstance(SourceFile:1)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.base.BaseDateTime.<init>(SourceFile:1)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTime.<init>(SourceFile:1)
08-10 14:17:09.244 22340 22456 E assert  : 	at org.joda.time.DateTime.now(SourceFile:1)
```
Enable R8 fullMode, or just use Gradle plugin 8+.
Given the aggressive way of R8 removing the reflective code, there shall be more strict rules in proguard-rules.pro or @Keep placed somewhere. 

https://issuetracker.google.com/issues/271675881
https://issuetracker.google.com/issues?q=R8%20FullMode

**Comment by samoylenkodmitry** [comment]
I think the problem is in my code, @Keep annotation around DateTimeZoneProvider solved the problem.
